# fly.toml app configuration file generated for side on 2023-07-28T16:06:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "content-diary"
primary_region = "nrt"

[build.args]
  RELEASE="content_diary"
  MIX_ENV="prod"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
