defmodule Core.Repo.Migrations.AddUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
    end

    create unique_index(:user, [:email], name: "user_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:user, [:email], name: "user_unique_email_index")

    drop table(:user)
  end
end