defmodule Core.Repo.Migrations.Extensions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user) do
      modify :hashed_password, :text, null: false
      modify :comment, :text, null: true, default: nil
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:schedule) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:joining_request) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end
  end

  def down do
    alter table(:joining_request) do
      modify :id, :uuid, default: nil
    end

    alter table(:schedule) do
      modify :id, :uuid, default: nil
    end

    alter table(:user) do
      modify :id, :uuid, default: nil
      modify :comment, :text, null: false, default: ""
      modify :hashed_password, :text, null: true
    end
  end
end