defmodule Core.Repo.Migrations.AlterJoiningRequestToSoftDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:joining_request) do
      add :deleted_at, :utc_datetime
    end

    drop_if_exists unique_index(:joining_request, [:contact],
                     name: "joining_request_contact_index"
                   )

    create unique_index(:joining_request, [:contact],
             where: "deleted_at IS NULL",
             name: "joining_request_contact_index"
           )
  end

  def down do
    drop_if_exists unique_index(:joining_request, [:contact],
                     name: "joining_request_contact_index"
                   )

    create unique_index(:joining_request, [:contact], name: "joining_request_contact_index")

    alter table(:joining_request) do
      remove :deleted_at
    end
  end
end