defmodule Core.Repo.Migrations.AddSchedule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:schedule, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :since, :utc_datetime, null: false
      add :until, :utc_datetime, null: false
      add :type, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :owner_id,
          references(:user,
            column: :id,
            name: "schedule_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :pair_id,
          references(:schedule,
            column: :id,
            name: "schedule_pair_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:schedule, "schedule_owner_id_fkey")

    drop constraint(:schedule, "schedule_pair_id_fkey")

    drop table(:schedule)
  end
end