defmodule Core.Repo.Migrations.AlterJoiningRequestRemoveAgeAddBirth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user) do
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :gender, :text, null: false
      add :birth, :date, null: false
      add :level, :text, null: false
      add :purpose, :text, null: false
      add :comment, :text, null: false, default: ""
      add :kakao_profile, :text
    end

    alter table(:joining_request) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :age

      add :birth, :date
    end
  end

  def down do
    alter table(:joining_request) do
      remove :birth
      # This is the `down` migration of the statement:
      #
      #     remove :age
      #

      add :age, :bigint
    end

    alter table(:user) do
      remove :kakao_profile
      remove :comment
      remove :purpose
      remove :level
      remove :birth
      remove :gender
      remove :last_name
      remove :first_name
    end
  end
end
